<a href="https://colab.research.google.com/github/Carlos2000-JGR/Practica-Individual-1/blob/main/Lab_Inteligenia_Artificial_Diego_Javier_1087228.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Write a Python program to print the following string in a specific format (see the output).  Sample String : "Twinkle, twinkle, little star, How I wonder what you are! Up above the world so high, Like a diamond in the sky. Twinkle, twinkle, little star, How I wonder what you are" Output : 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
print("Twinkle, twinkle, little star,\n\ta.How I wonder what you are!\n\t\ti.Up above the world so high,\n\t\tii.Like a diamond in the sky.\nTwinkle, twinkle, little star,\n\tb.How I wonder what you are")

Twinkle, twinkle, little star,
	a.How I wonder what you are!
		i.Up above the world so high,
		ii.Like a diamond in the sky.
Twinkle, twinkle, little star,
	b.How I wonder what you are


2.Write a Python program to get the Python version you are using.

In [ ]:
import sys
print(sys.version)

3.7.15 (default, Oct 12 2022, 19:14:55) 
[GCC 7.5.0]


3.Write a Python program to display the current date and time.
Sample Output :
Current date and time :
2014-07-05 14:34:14

In [ ]:
from datetime import datetime
hoy = datetime.now()

hoy_string = hoy.strftime("%d/%m/%Y %H:%M:%S")
print(hoy_string)

23/11/2022 16:09:23



4.Write a Python function which accepts the radius of a circle from the user and compute the area. 
Sample Output :
r = 1.1
Area = 3.8013271108436504


In [ ]:
import math
radio = float(input("Introduzca el area del circulo:"))
area = math.pi * pow(radio, 2)
print(area)

Introduzca el area del circulo:1.1
3.8013271108436504


 5.Write a Python program which accepts the user's first and last name and print them in reverse order with a space between them.

In [ ]:
st = input("introduzca el string: ")
stringlength=len(st)
slicedString=st[stringlength::-1] 
print(slicedString)

introduzca el string: diego javier
reivaj ogeid


6.Write a Python program which accepts a sequence of comma-separated numbers from user and generate a list and a tuple with those numbers.  Sample data : 3, 5, 7, 23
Output :
List : ['3', ' 5', ' 7', ' 23']
Tuple : ('3', ' 5', ' 7', ' 23')

In [ ]:
secuencia6 = input("Introduzca la secuencia: ")
lista = secuencia6.split(",")
tuple = tuple(lista)
print("List: ",lista, "\nTuple: ",tuple)

Introduzca la secuencia: 3, 5, 7, 23
List:  ['3', ' 5', ' 7', ' 23'] 
Tuple:  ('3', ' 5', ' 7', ' 23')


7.Write a Python function to accept a filename from the user and print the extension of that.  Sample filename : abc.java
Output : java


In [ ]:
text1 = "/content/abc.txt"
file1 = open(text1, "r")
filecontent = file1.read()
print(filecontent)


java


8.Write a function that returns the maximum of a tuple or array numbers.

In [ ]:
import numpy as np
def secuencias():
  Nuevasecuencia = []
  iteracion = int(input("introduzca la cantidad de valores del array: "))
  for x in range(iteracion):
    nuevoValor = float(input("ingrese los valores: "))
    Nuevasecuencia.append(nuevoValor)
  return np.amax(Nuevasecuencia)


print("El numero mas grande es: ", secuencias())

introduzca la cantidad de valores del array: 3
ingrese los valores: 3
ingrese los valores: 78
ingrese los valores: 24
El numero mas grande es:  78.0


9.Write a function called fizz_buzz that takes a number.
If the number is divisible by 3, it should return “Fizz”.
If it is divisible by 5, it should return “Buzz”.
If it is divisible by both 3 and 5, it should return “FizzBuzz”.
Otherwise, it should return the same number.


In [ ]:
def fizz_buzz(numero):
    if(numero %3 == 0 and numero %5 == 0):
      print("fizz buzz")
    elif(numero %3 == 0):
      print("fizz")
    elif(numero %5 == 0):
      print("buzz")
    else:
      print(numero)

Number = int(input("introduzca el valor: "))
fizz_buzz(Number)

introduzca el valor: 15
fizz buzz


10.Write a function for checking the speed of drivers. This function should have one parameter: speed.
If speed is less than 70, it should print “Ok”.
Otherwise, for every 5km above the speed limit (70), it should give the driver one demerit point and print the total number of demerit points. For example, if the speed is 80, it should print: “Points: 2”.
If the driver gets more than 12 points, the function should print: “License suspended”


In [ ]:
def police(speed):
  if(speed <= 70):
    print("Ok.")
  else:
    points = math.floor((speed - 70)/5)
    if(points < 12):
       print("Points: " ,points)
    else:
       print("License suspended")


Speed = int(input("velocidad actual del vehiculo en km/s: "))
police(Speed)


velocidad actual del vehiculo en km/s: 83
Points:  2


11. Write a function called showNumbers that takes a parameter called limit. It should print all the numbers between 0 and limit with a label to identify the even and odd numbers. For example, if the limit is 3, it should print:
0 EVEN
1 ODD
2 EVEN
3 ODD



In [ ]:
def showNumbers(limit):
  for x in range(limit + 1):
    if(x%2 == 0):
      print(x, "EVEN")
    else:
      print(x, "ODD")




limite = int(input("Introduzca el valor: "))
showNumbers(limite)

Introduzca el valor: 5
0 EVEN
1 ODD
2 EVEN
3 ODD
4 EVEN
5 ODD


12. Write a function that returns the sum of multiples of 3 and 5 between 0 and limit (parameter). For example, if limit is 20, it should return the sum of 3, 5, 6, 9, 10, 12, 15, 18, 20.


In [ ]:
 def calculate_sum(limit):
    total = 0
    for i in range(limit + 1):
        if(i %3 == 0 or i %5 == 0):
           total = total + i
        i = i + i
    return total

limit = int(input("introduzca el valor: "))
print("Total sum: " + str(calculate_sum(limit)))

introduzca el valor: 20
Total sum: 98


13. Write a function called show_stars(rows). If rows is 5, it should print the following:
*
**
***
****
*****


In [ ]:
def show_stars(rows):
  star = "*"
  for x in range(rows):
    print(star)
    star = star + "*"

row = int(input("introduzca el valor: "))
show_stars(row)

introduzca el valor: 5
*
**
***
****
*****


14.Write a function that prints all the prime numbers between 0 and limit where limit is a parameter.

In [ ]:
def prime(limit):
   primeso = []
   for n in range(2, limit):
      for i in range (2, limit+1):
         for j in range(2, i):
             if i%j == 0:
                 break
         else:
             primeso.append(i)
   print(primeso)


primo = int(input("introduzca el valor: "))
prime(primo)

introduzca el valor: 10
[2, 3, 5, 7, 2, 3, 5, 7, 2, 3, 5, 7, 2, 3, 5, 7, 2, 3, 5, 7, 2, 3, 5, 7, 2, 3, 5, 7, 2, 3, 5, 7]


15 .Write a Python program to print all even numbers from a given numbers list in the same order and stop the printing if any numbers that come after 237 in the sequence.  

In [ ]:
numbers = [    
     386, 462, 47, 418, 907, 344, 236, 375, 823, 566, 597, 978, 328, 615, 953, 345, 
     399, 162, 758, 219, 918, 237, 412, 566, 826, 248, 866, 950, 626, 949, 687, 217, 
     815, 67, 104, 58, 512, 24, 892, 894, 767, 553, 81, 379, 843, 831, 445, 742, 717, 
     958,743, 527
     ]

for x in numbers:
     if x == 237:
         print(x)
         break;
     elif x % 2 == 0:
         print(x)

386
462
418
344
236
566
978
328
162
758
918
237


16. Write a Python program that will accept the base and height of a triangle and compute the area. 


In [ ]:
base = int(input("introduzca la base: "))
altura = int(input("introduzca la altura: "))
area = (base * altura)/2
print("el area es de ", area)

introduzca la base: 5
introduzca la altura: 10
el area es de  25.0


17.Write a Python program to compute the greatest common divisor (GCD) of two positive integers. 


In [ ]:
def gcd(x, y):
   gcd = 1   
   if x % y == 0:
       return y   
   for k in range(int(y / 2), 0, -1):
      if x % k == 0 and y % k == 0:
          gcd = k
          break 
   return gcd

primervalor = int(input("introduzca el valor 1:"))
segundovalor = int(input("introduzca el valor 2:"))
print("GCD es =",gcd(primervalor, segundovalor))

introduzca el valor 1:2
introduzca el valor 2:40
GCD es = 2


18.Write a Python program to get the least common multiple (LCM) of two positive integers.


In [ ]:
def lcm(x, y):
  if x > y:
      z = x
  else:
      z = y
  while(True):
      if((z % x == 0) and (z % y == 0)):
          lcm = z
          break
      z += 1
  return lcm

primervalor = int(input("introduzca el valor 1:"))
segundovalor = int(input("introduzca el valor 2:"))
print("LCM es: ", lcm(primervalor, segundovalor))

introduzca el valor 1:4
introduzca el valor 2:6
LCM es:  12


19.Write a Python program to sum of three given integers. However, if two values are equal sum will be zero.


In [ ]:
def sum(x, y, z):
    if x == y or y == z or x==z:
        sum = 0
    else:
        sum = x + y + z
    return sum
primervalor = int(input("introduzca el valor 1:"))
segundovalor = int(input("introduzca el valor 2:"))
tercervalor = int(input("introduzca el valor 3: "))
print(sum(primervalor, segundovalor, tercervalor))

introduzca el valor 1:3
introduzca el valor 2:2
introduzca el valor 3: 1
6


20. Write a Python function that takes a sequence of numbers and determines whether all the numbers are different from each other. 

In [ ]:
def test_distinct(data):
  if len(data) == len(set(data)):
    return True
  else:
    return False;

print(test_distinct([1,5,7,9]))

21.Write a Python program to create all possible strings by using 'a', 'e', 'i', 'o', 'u'. Use the characters exactly once. 


In [ ]:
import random
char_list = ['a','e','i','o','u']
random.shuffle(char_list)
print(''.join(char_list))

ieoau


22.write a Python program to check the sum of three elements (each from an array) from three arrays is equal to a target value. Print all those three-element combinations. 

In [ ]:
from functools import partial
X = [10, 20, 20, 20]
Y = [10, 20, 30, 40]
Z = [10, 30, 40, 20]
T = 70

def check_sum_array(N, nums):
  if sum(x for x in nums) == N:
    return (True, nums)
  else:
      return (False, nums)
      
pro = itertools.product(X,Y,Z)
func = partial(check_sum_array, T)
sums = list(itertools.starmap(func, pro))

result = set()
for s in sums:
    if s[0] == True and s[1] not in result:
      result.add(s[1])
      print(result)

23.Write a NumPy program to create an array of all the even integers from 30 to 70.  

In [ ]:
import numpy as np
array = np.arange(30,71,2)
print("Resultado: ")
print(array) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


24.Write a NumPy program to create a 3x3 identity matrix.  


In [ ]:
matrix=np.identity(3)
print('3x3 matrix:')
print(matrix)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


25.Write a NumPy program to generate a random number between 0 and 1.  


In [ ]:
rand_num = np.random.normal(0,1,1)
print("El valor random sera: ")
print(rand_num)

Random number between 0 and 1:
[-0.79935519]


26.Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.  


In [ ]:
rand_num = np.random.normal(0,1,15)
print("El arreglo estara conformado de: ")
print(rand_num)

El arreglo estara conformado de: 
[ 0.90020903 -0.10179557 -0.36178909  1.08997562 -1.34314078 -1.62746666
 -0.13669836 -1.05831681  1.3866888  -0.13797451 -0.75961217  0.25440995
  0.40014947 -1.92084615  1.56228078]


27.Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.


In [ ]:
v = np.arange(15,55)
print("vector inicial:")
print(v)
print("Vector sin el primer y ultimo valor: ")
print(v[1:-1])

vector inicial:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
Vector sin el primer y ultimo valor: 
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


28.write a Python program which solve the equation: 

In [ ]:
print("Input the value of a, b, c, d, e, f:")
a, b, c, d, e, f = map(float, input().split())
n = a*e - b*d
print("Values of x and y:")
if n != 0:
    x = (c*e - b*f) / n
    y = (a*f - c*d) / n
    print('{:.3f} {:.3f}'.format(x+0, y+0))

Input the value of a, b, c, d, e, f:
1 2 3 4 5 6
Values of x and y:
-1.000 2.000


29. Write a Python program to compute the amount of the debt in n months. The borrowing amount is $100,000 and the loan adds 5% interest of the debt and rounds it to the nearest 1,000 above month by month. 

In [ ]:
def round_n(n):
    if n%1000:
        return (1+n//1000)*1000
    else:
        return n
def compute_debt(n):
    if n==0: return 100000
    return int(round_n(compute_debt(n-1)*1.05))

print("Cantidad de mese")
result = compute_debt(int(input()))
print("Amount of debt: ","$"+str(result).strip())

Input number of months:
4
Amount of debt:  $123000


30. Write a Python function to print the number of prime numbers which are less than or equal to a given integer.  


In [ ]:
primes = [1] * 500000
primes[0] = 0
 
for i in range(3, 1000, 2):
    if primes[i // 2]:
        primes[(i * i) // 2::i] = [0] * len(primes[(i * i) // 2::i])
 
print("Introduzca el valor :")
n=int(input())
if n < 4:
    print("Numero primos que son menor o igual que el valor dado",n - 1)
else:
    print("Numero primos que son menor o igual que el valor dado",sum(primes[:(n + 1) // 2]) + 1)

Introduzca el valor :
5
Numero primos que son menor o igual que el valor dado 3
